version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: dev
      DB_PASSWORD: dev
      DB_DATABASE: dev
    ports:
      - "3000:3000"
    command: yarn run start:dev

volumes:
  db-data: